uploads = []
generated = []

[[outputs]]
id = "WzLsCVsvgLAnwYHwJH99S"
uri = "file:///home/runner/Life-Maintained-clean.tar.gz"
type = "unspecified"
title = "Life-Maintained-clean.tar.gz"

[[outputs]]
id = "FFkueSG_K9gq054gN9gQ5"
uri = "file://Life-Maintained-clean.tar.gz"
type = "unspecified"
title = "Life-Maintained-clean.tar.gz"
