import { matchServiceToTask } from "./serviceMatcher";
type T = { id: string; name: string };
const TASKS: T[] = [["t1","Air Filter Cleaning and Replacement"],["t2","Battery and Charging System Test"],["t3","Check Tire Pressure and Condition"],["t4","Drive Belt Inspection and Replacement"],["t5","Engine Oil and Filter Change"],["t6","Fuel System Cleaning"],["t7","Inspect Brake Pads"],["t8","Replace Brake Fluid"],["t9","Replace Coolant"],["t10","Replace Spark Plugs"],["t11","Steering and Suspension Inspection"],["t12","Transmission Fluid Inspection"],["t13","Wiper Blade Replacement"]].map(([id,name])=>({id,name}));
const AUTO: [string,string][] = [["oil change","t5"],["changed the oil","t5"],["oil & filter","t5"],["synthetic oil change","t5"],["did an oil change","t5"],["got my oil changed today","t5"],["5k mile oil change","t5"],["lube oil filter","t5"],["5w30 oil change","t5"],["mobil 1 oil change","t5"],["replaced spark plugs","t10"],["new spark plugs","t10"],["ignition coils replaced","t10"],["ngk plugs installed","t10"],["coolant flush","t9"],["replaced coolant","t9"],["antifreeze change","t9"],["radiator flush","t9"],["transmission fluid","t12"],["trans fluid service","t12"],["tranny fluid change","t12"],["atf change","t12"],["gearbox oil change","t12"],["replaced wiper blades","t13"],["new wipers","t13"],["bosch wiper blades installed","t13"],["drive belt replacement","t4"],["serpentine belt","t4"],["adjusted drive belt","t4"],["fan belt replaced","t4"],["serpentine fan belt","t4"],["fuel system cleaning","t6"],["fuel injector cleaning","t6"],["fuel injectors cleaned","t6"],["air filter replacement","t1"],["cabin air filter","t1"],["replaced battery","t2"],["hybrid battery check","t2"],["checked tire pressure","t3"],["checked tires","t3"],["aired up tires","t3"],["brake fluid flush","t8"],["replaced brake fluid","t8"],["dot4 brake fluid flush","t8"],["replaced brake pads","t7"],["brake pad replacement","t7"],["steering and suspension","t11"],["engine oil drain and fill","t5"],["transmission drain and fill","t12"],["coolant drain and fill","t9"],["spring oil change","t5"],["spark plug replaced","t10"],["battery load test","t2"],["battery","t2"],["coolant","t9"]];
const NOT: [string,string][] = [["replaced brake pads","t8"],["brake fluid flush","t7"],["coolant flush","t12"],["key fob battery","t2"],["oil leak repair","t5"],["transmission fluid","t8"],["transmission fluid","t9"],["rotated tires","t3"],["air filter change","t5"],["battery terminal cleaning","t2"],["transmission flush","t9"],["transmission flush","t8"],["wiper fluid top off","t13"],["wiper fluid","t13"],["radiator replaced","t9"],["coolant hose replaced","t9"],["fuel pump replaced","t6"],["fuel filter replaced","t6"],["spark plug wires","t10"],["battery cable replaced","t2"],["replaced coolant hoses","t9"],["battery cables replaced","t2"],["coolant sensors replaced","t9"],["spark plug boots replaced","t10"],["oil pan replaced","t5"],["oil cooler replaced","t5"],["oil dipstick replaced","t5"],["coolant reservoir replaced","t9"],["coolant thermostat replaced","t9"],["fuel tank replaced","t6"],["fuel door replaced","t6"],["fuel rail cleaned","t6"],["battery tray replaced","t2"],["wiper arm replaced","t13"],["transmission pan replaced","t12"],["steering rack replaced","t11"],["glow plugs replaced","t10"],["transmission rebuild","t12"],["dead battery","t2"],["battery died","t2"],["jumped the battery","t2"],["suspension springs replaced","t11"],["steering column replaced","t11"]];
const DEC: [string,string][] = [["brakes","REVIEW"],["brake service","REVIEW"],["fluid","REVIEW"],["inspection","REVIEW"],["service","NONE|REVIEW"],["belt","REVIEW"],["windshield chip repair","NONE|REVIEW"],["car wash","NONE"],["detailing","NONE"],["new headlight bulb","NONE"],["paint touch up","NONE"],["topped off coolant","REVIEW"],["pads and rotors","REVIEW"],["oil change and tire rotation","REVIEW"],["differential fluid","NONE|REVIEW"],["washer fluid refill","NONE"],["ac recharge","NONE"],["lof","NONE"],["cooling fan replaced","NONE|REVIEW"],["radiator fan replaced","NONE"],["glow plugs replaced","NONE|REVIEW"],["transmission rebuild","NONE|REVIEW"],["oil change due","REVIEW"],["oil change overdue","REVIEW"],["declined transmission service","NONE|REVIEW"],["next oil change","REVIEW"],["spark plugs recommended","REVIEW"],["coolant flush recommended not done","NONE|REVIEW"],["scheduled oil change","REVIEW"],["shift linkage replaced","NONE|REVIEW"],["piston rings replaced","NONE|REVIEW"],["wheel bearing replaced","NONE|REVIEW"],["glow plug replaced","NONE|REVIEW"]];
let hard = 0; const soft: string[] = [];
for (const [i,e] of AUTO) { const o = matchServiceToTask(i, TASKS); if (o.decision === "AUTO" && o.task && o.task.taskId === e) { /* pass */ } else if (o.decision === "AUTO") { hard++; console.log("  WRONG-AUTO", i, "->", o.task ? o.task.taskId : "-"); } else soft.push(i + " -> " + o.decision + " want AUTO " + e); }
for (const [i,f] of NOT) { const o = matchServiceToTask(i, TASKS); if (o.decision === "AUTO" && o.task && o.task.taskId === f) { hard++; console.log("  FORBIDDEN", i, "->", f); } }
for (const [i,e] of DEC) { const o = matchServiceToTask(i, TASKS); if (o.decision === "AUTO") { hard++; console.log("  SHOULD-NOT-AUTO", i); } else if (!e.split("|").includes(o.decision)) soft.push(i + " -> " + o.decision + " want " + e); }
console.log(soft.length ? "SOFT (" + soft.length + "): " + soft.join(" | ") : "SOFT: none");
if (hard === 0) { console.log("TRUTHTABLE HARD PASS"); } else { throw new Error("TRUTHTABLE HARD FAIL (" + hard + ")"); }
